apiVersion: v1
kind: Pod
metadata:
  name: disk-pod-ssd
spec:
  containers:
  - name: disk-pod-ssd
    image: nginx
#    command: ["/bin/sh"]
#    stdin: true
#    tty: true
#    imagePullPolicy: Always
    volumeMounts:
    - name: disk-pvc
      mountPath: /mnt
  volumes:
    - name: disk-pvc
      persistentVolumeClaim:
        claimName: disk-ssd
  restartPolicy: Never