apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  #17字节密码 oMm5AAE86DUFe3MK 设置后无效，原因未知
#  MYSQL_ROOT_PASSWORD: b01tNUFBRTg2RFVGZTNNSwo=
#删除一个字符 oMm5AAE86DUFe3M 就可以了 难道不能超过16字节？
  MYSQL_ROOT_PASSWORD: b01tNUFBRTg2RFVGZTNN