apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  mysql.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
    max_connections = 1000
    query_cache_size = 0
    innodb_buffer_pool_size = 256M # (adjust value here, 50%-70% of total RAM)
    innodb_log_file_size = 512M
    innodb_flush_log_at_trx_commit = 1 # may change to 2 or 0
    innodb_flush_method = O_DIRECT
    lower_case_table_names = 1

    [mysql]

    [mysqldump]
    quick
    quote-names
    max_allowed_packet = 16M