apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: test-container
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      args: ["/bin/sh"]
      stdin: true
      tty: true
  restartPolicy: Never