apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
    - name: tcp
      port: 61616
      targetPort: 61616
    - name: http
      port: 8161
      targetPort: 8161
  selector:
    app: activemq
  type: LoadBalancer