apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo-client
  labels:
    app: demo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-client
  template:
    metadata:
      labels:
       app: demo-client
    spec:
      containers:
      - name: demo-client
        image: yeshuangming/spring-cloud-with-eureka-demo-client:0.0.1-SNAPSHOT
        ports:
        - name: http
          containerPort: 9100