apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
    args: ["/bin/sh"]
    name: test-container
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never